#!/usr/bin/env bash
# Mint a STATIC bearer-token kubeconfig for the opt-in EKS test cluster and write
# it to the fixed path docker-compose mounts (build/.e2e-kubeconfig).
#
# ADR-0010: the distroless Kubescope image has no `aws` CLI, so an exec-based EKS
# kubeconfig (`exec: aws eks get-token`) cannot run in-container. Instead we mint
# a short-lived bearer token here on the HOST and embed it — no exec stanza, no
# AWS credentials in the container, shipped image unchanged.
#
# The token is a ~15-min STS presigned URL. Past expiry the dashboard returns
# 401s; just re-run this command (make e2e-eks-kubeconfig) to refresh it.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT="${KUBESCOPE_COMPOSE_KUBECONFIG:-$REPO_ROOT/build/.e2e-kubeconfig}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "$1 not found — $2" >&2; exit 1; }; }
need terraform "needed to read the cluster outputs."
need aws "needed to mint the EKS bearer token."
need jq "needed to parse the token JSON."

cd "$SCRIPT_DIR"
if ! terraform output -raw cluster_name >/dev/null 2>&1; then
  echo "no Terraform outputs found — run 'make e2e-eks-up' first." >&2
  exit 1
fi

cluster="$(terraform output -raw cluster_name)"
endpoint="$(terraform output -raw cluster_endpoint)"
ca="$(terraform output -raw cluster_certificate_authority_data)"
region="$(terraform output -raw region)"

echo "Minting a ~15-min bearer token for $cluster ($region) ..."
token="$(aws eks get-token --cluster-name "$cluster" --region "$region" --output json | jq -r '.status.token')"
[ -n "$token" ] && [ "$token" != "null" ] || { echo "failed to mint a token — check your AWS credentials." >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
umask 077
cat > "$OUT" <<EOF
# Static token-kubeconfig for the EKS e2e cluster — generated by
# deploy/e2e-eks/kubeconfig.sh (ADR-0010). NO exec stanza, NO AWS creds.
# Token TTL ~15 min; re-run 'make e2e-eks-kubeconfig' to refresh.
apiVersion: v1
kind: Config
current-context: $cluster
clusters:
- name: $cluster
  cluster:
    server: $endpoint
    certificate-authority-data: $ca
contexts:
- name: $cluster
  context:
    cluster: $cluster
    user: $cluster
users:
- name: $cluster
  user:
    token: $token
EOF
chmod 600 "$OUT"

echo "Wrote static token-kubeconfig → $OUT"
echo "Launch:  make compose-up      (build the image first if needed: make docker-build-local)"
echo "Token expires in ~15 min — re-run 'make e2e-eks-kubeconfig' when the dashboard starts returning 401s."
